#!/bin/bash

rm -f csh-out shell-out
echo "issue-53: echo \"*\""
touch yash-in bash-in bash-out yash-out
mkdir -p a

echo "echo *" > yash-in
echo "echo *" > bash-in
echo "echo \"*\"" >> yash-in
echo "echo \"*\"" >> bash-in

/bin/bash < bash-in > bash-out 2>&1
../src/yash < yash-in > yash-out 2>&1

rm -rf a

diff yash-out bash-out
if [ $? -ne 0 ]
then
    echo "Issue 53 regression test failed"
    exit -1
fi
echo issue-53-test OK
exit 0
