#!/bin/sh

##
# This script tests issue #25 for YaSh
##

rm -f sh-out shell-out

echo "Test 25: Multi Arg CD"

mkdir cs240
mkdir cs252

echo "cd cs240" > shell-in
echo "cd 240 252" >> shell-in
echo "pwd" >> shell-in

expected="$(pwd)/cs252"
echo $expected > sh-out

../shell < shell-in > shell-out

rm -rf cs240 cs252

diff shell-out sh-out

if [ $? -ne 0 ]; then
    echo "Test-25 failed"
    exit -1
fi

echo Test-25 OK

