#!/bin/sh

rm -f csh-out yash-out
echo "Test112: echo /etc/r*/*s* "
echo "echo /etc/r*/*s*" > yash-in

/bin/bash < yash-in > bash-out 2>&1
../src/yash < yash-in > yash-out 2>&1

_diff=$(diff yash-out bash-out)
if [ $? -ne 0 ]
then
    echo "Test112 failed"
    echo "========= Got =========="
    cat yash-out
    echo "======= Expected ======="
    cat bash-out
    echo "====== Difference ======"
    echo ${_diff}
    exit 1
fi
echo Test112 OK
exit 0
