stages:
  - build
  - test
  - deploy

yash:
  stage: build
  script:
    - ./autogen.sh
    - automake --add-missing
    - autoconf
    - ./configure
    - make -j5

tests:
  stage: test
  script:
    - ./autogen.sh
	- ./configure
	- make -j5
	- ln -sf $(pwd)/src/yash $(pwd)/shell
	- cd test
	- ./testall

distribute:
  stage: deploy
  script:
    - ./autogen.sh
    - ./configure
    - make -j5
    - make dist
    - mv *.tar.gz yash-$(date +%Y-%m-%d-%H-%M-%S).tar.gz
  artifacts:
    paths:
      - ./*.tar.gz
    expire_in: 1 week
