language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo wget -O uncrustify.deb http://mirrors.kernel.org/ubuntu/pool/universe/u/uncrustify/uncrustify_0.65+git20170831+dfsg1-1_amd64.deb
  - sudo wget -O libc.deb http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.26-0ubuntu2.1_amd64.deb
  - sudo wget -O libstdc++.deb http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/libstdc++6_7.2.0-8ubuntu3.2_amd64.deb
  - sudo dpkg -i uncrustify.deb libstdc++.deb libc.deb

script:
  - test/run-linter.bash
  - ./autogen.sh
  - ./configure
  - make -j$(nproc)
  - ln -sf $(pwd)/src/yash $(pwd)/shell
  - cd test
  - export LC_COLLATE="C"
  - ./testall
