language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  # C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - ln -sf $(pwd)/yash $(pwd)/../shell
  - ln -sf $(pwd)/yash $(pwd)/../src/yash
  - cd ../test
  - export LC_COLLATE="C"
  - export IS_TRAVIS="YES"
  - ./testall
