#!/bin/bash

old_lc=$LC_ALL
export LC_ALL=C
rm -f csh-out shell-out
echo "issue-33: echo ../../test/*"
touch yash-in bash-in bash-out yash-out
mkdir -p a

echo "cd a" > yash-in
echo "cd a" > bash-in
echo "echo ../../test/*" >> yash-in
echo "echo ../../test/*" >> bash-in

/bin/bash < bash-in > bash-out 2>&1
${SHELL_BIN} < yash-in > yash-out 2>&1

rm -rf a

export LC_ALL=$old_lc
_diff=$(diff yash-out bash-out)
if [ $? -ne 0 ]
then
    echo "Issue 33 regression test failed"
    echo "====== Got ======="
    cat yash-out
    echo "====== Expected ====="
    cat bash-out
    echo "====== Difference ====="
    echo ${_diff}
    exit 1
fi
echo issue-33-test OK
exit 0
