#!/bin/sh

rm csh-out shell-out
echo "Test104: cd ${HOME}; pwd"
echo "cd ${HOME}" > shell-in
echo "/bin/pwd" >> shell-in 

/bin/sh < shell-in > csh-out 2>&1
${SHELL_BIN} < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test104 failed"
    exit -1
fi
echo Test104 OK
exit 0
